# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a55bf6bc96a99cdd96d59d7dc03c29e223a0aa38e802361f41569b5ca9a68abe6f88d6055cf49de5a3c6e52712055305746a7bf4b3034210b446570616297fc1

test:
  secret_key_base: 78654a72d79b77f578d7da5af7ac5e4af28b1b0e40cc4c94ef60688462e707f369ad5e2cec05d28fd7ae1720949ffc2664481974918676b225ca9c54bc4eef65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
